version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - run:
          name: The First Step
          command: |
            cd..
            gcc helloworld.c -o Output